---
title: Teaching
author: Boris Hejblum
font-size: "font_size_small"
date: '2016-09-27'
slug: teach
---


</br>

## *Short courses*

***

### Doctoral training

 * [Bayesian methods in medical research](https://bayesbiomed.borishejblum.science) --- *University of Copenhagen* (2019 -- 2024)
 * [endeav`r fontawesome::fa("r-project")`: *code efficiency and software development with* `r fontawesome::fa("r-project")`](https://endeavr.borishejblum.science) -- *Université de Bordeaux* (2018, 2022, 2023)  
    + [`r fontawesome::fa("r-project")` codes](https://github.com/borishejblum/mypkgr/archive/refs/tags/v2022.tar.gz)
    + French version: [`r fontawesome::fa("r-project")` **avancé :** *outils de développement et de performance*](https://r-dev-perf.borishejblum.science)

### International Summer School -- [ISPED](http://www.isped.u-bordeaux.fr/Formation/Ecoled%C3%A9t%C3%A9.aspx)/[Bordeaux School of Public Health](http://bss-publichealth.u-bordeaux.fr/en/Program/Course-n-1-Statistical-analysis-of-big-data-linked-to-immunology-systems/r742.html)
  
  * [BAsics for DAta Science with R](/badas) (2019)
  * Statistical analysis of big data linked to immunology systems (2017, 2019)
  * Introduction to Bayesian Analysis (2018)


</br>

## *Books*

***

  * [*Vers une recherche reproductible*](https://rr-france.github.io/bookrr/), Desquilbet, Granger, Hejblum, Legrand, Pernot & Rougier, 2019.
  


</br>

## *Courses*

***

### M2 Public Health Data Science -- ISPED, Université de Bordeaux
  
  * OMICS (2019 -- ...)  
   [Transcriptomics slides](/files/transcriptomics-eur/TranscriptomicsData.pdf) | <a href="/html/m2phds-omics/transcriptomics_M2PHDS_OMICS_practicals.html" target="_blank"> practicals </a> | [data](/files/transcriptomics-eur/SinghaniaTB_data.Rdata) | <a href="/html/m2phds-omics/transcriptomics_M2PHDS_OMICS_practicals_solutions.html" target="_blank">solutions </a>  
   [Multiple testing slides](/files/transcriptomics-eur/MultiTests_Slides.pdf) | <a href="/html/m2phds-omics/multitests_M2PHDS_OMICS_practicals.html" target="_blank"> practicals </a>
  * BASICS (2019 -- 2022)  
  <a href="/html/m2phds-basics/biostatistics_basics_MLEslides.html" target="_blank">MLE slides</a> | <a href="/html/m2phds-basics/biostatistics_basics_MLEpracticals.html" target="_blank">MLE practicals</a> | [data](/files/birthweight_data.txt) | <a href="/html/m2phds-basics/biostatistics_basics_MLEpracticals_solutions.html" target="_blank">solutions</a>  
  <a href="/html/m2phds-basics/biostatistics_basics_REGslides.html" target="_blank">Regression slides</a> 
   

### M2 *Biostatistique* -- ISPED, Université de Bordeaux

  * [STA305 Approche bayésienne et méthodes numériques pour la statistique (2016 -- 2022)](https://sta305bayes.borishejblum.science)  
  <a href="/files/STA305cours_etud.pdf" target="_blank">cours</a> | <a href="/files/STA305slides_Bayes.pdf" target="_blank">Diapos Bayes</a> | <a href="/files/STA305slides_MCMC.pdf" target="_blank">Diapos MCMC</a> | <a href="/html/STA305/STA305_TP_enonce.html" target="_blank">Travaux pratiques</a> <!-- - <a href="/html/STA305/STA305_TP_correction.html" target="_blank">correction</a> -->| <a href="/files/ExamBayes_20132014_ALL_COR.pdf" target="_blank">Correction exam 2014</a>
  
  * STA206 Analyse de données multivariées (2016 -- 2018)


### M1 *Santé Publique* -- ISPED, Université de Bordeaux

  * EPI101 Data visualisation (2022 -- ...)
  * STA102 Méthodes factorielles et classification (2019 -- 2021)
  * STA101 Tests Statistiques (2016 -- 2018)


